# Generated by Django 6.0 on 2026-01-23 00:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('ASESOR', 'Asesor (Oferente)'), ('CLIENTE', 'Cliente (Busca servicio)')], default='CLIENTE', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('timezone', models.CharField(default='America/Santiago', max_length=50, verbose_name='Zona Horaria')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Móvil')),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True, verbose_name='WhatsApp')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AsesorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(default='Consultor', max_length=100, verbose_name='Especialidad')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Biografía Completa')),
                ('public_title', models.CharField(help_text='Ej: Experto en Python', max_length=100, verbose_name='Título Público')),
                ('experience_summary', models.TextField(verbose_name='Resumen de Experiencia')),
                ('hourly_rate', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Tarifa por Hora (CLP)')),
                ('is_approved', models.BooleanField(default=False, verbose_name='¿Aprobado por Admin?')),
                ('meeting_link', models.URLField(blank=True, null=True, verbose_name='Enlace a Sala de Reunión')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asesor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Fecha/Hora Inicio')),
                ('end_datetime', models.DateTimeField(verbose_name='Fecha/Hora Fin')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('POR_PAGAR', 'Aprobada - Esperando Pago'), ('CONFIRMADA', 'Pagada y Confirmada'), ('FINALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada'), ('REEMBOLSADO', 'Dinero Devuelto')], default='PENDIENTE', max_length=20)),
                ('meeting_link', models.URLField(blank=True, null=True, verbose_name='Enlace a Sala de Reunión (Zoom/Meet)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('client_city', models.CharField(blank=True, max_length=100, null=True)),
                ('client_address', models.CharField(blank=True, max_length=255, null=True)),
                ('client_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('reclamo_mensaje', models.TextField(blank=True, help_text='Razón del reclamo del cliente', null=True)),
                ('estado_reclamo', models.CharField(choices=[('SIN_RECLAMO', 'Sin Reclamo'), ('PENDIENTE', 'Revisión Pendiente (Jefe)'), ('APROBADO', 'Reembolso Aprobado'), ('RECHAZADO', 'Reclamo Rechazado')], default='SIN_RECLAMO', max_length=20)),
                ('payment_token', models.CharField(blank=True, help_text='Referencia interna, NO es la tarjeta.', max_length=100, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asesor_appointments', to='core.asesorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora Inicio')),
                ('end_time', models.TimeField(verbose_name='Hora Fin')),
                ('is_booked', models.BooleanField(default=False)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='core.asesorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('transaction_id', models.CharField(max_length=100, verbose_name='ID MercadoPago')),
                ('payment_status', models.CharField(default='approved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.appointment')),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.asesorprofile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Desde')),
                ('end_date', models.DateField(verbose_name='Hasta')),
                ('reason', models.CharField(default='Vacaciones', max_length=200, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.asesorprofile')),
            ],
        ),
    ]
