# Generated by Django 6.0 on 2026-01-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_birth_date_user_mobile_user_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Pega aquí tu link de Zoom o Google Meet personal', null=True, verbose_name='Enlace a Sala de Reunión (Zoom/Meet)'),
        ),
    ]
