# Generated by Django 6.0 on 2026-01-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_appointment_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesorprofile',
            name='meeting_link',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace a Sala de Reunión'),
        ),
    ]
