# Generated by Django 6.0 on 2026-01-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chatmessage_delete_adminmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesorprofile',
            name='active_days',
            field=models.CharField(blank=True, default='', help_text='Días activos (0=Lunes, 6=Domingo)', max_length=50),
        ),
        migrations.AddField(
            model_name='asesorprofile',
            name='active_hours',
            field=models.TextField(blank=True, default='', help_text='Lista de horas activas separadas por coma'),
        ),
        migrations.AddField(
            model_name='asesorprofile',
            name='auto_schedule',
            field=models.BooleanField(default=False, verbose_name='Modo Automático'),
        ),
    ]
