# Generated by Django 6.0 on 2026-01-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_asesorprofile_active_days_asesorprofile_active_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='estado_solicitud',
            field=models.CharField(choices=[('NINGUNA', 'Sin Solicitud'), ('PENDIENTE', 'Solicitud Pendiente'), ('APROBADA', 'Cambio Aprobado (Pagar Multa)'), ('FINALIZADA', 'Cambio Realizado'), ('RECHAZADA', 'Solicitud Rechazada')], default='NINGUNA', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='motivo_cambio',
            field=models.TextField(blank=True, help_text='Motivo por el cual quiere cambiar la hora', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='multa_pagada',
            field=models.BooleanField(default=False, help_text='¿Pagó el 15% de recargo?'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='solicitud_cambio',
            field=models.BooleanField(default=False, help_text='¿El cliente solicitó cambiar la hora?'),
        ),
    ]
