# Generated by Django 6.0 on 2026-01-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appointment_estado_solicitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment_token',
            field=models.CharField(blank=True, help_text='Referencia interna', max_length=100, null=True),
        ),
    ]
