# Generated by Django 6.0 on 2026-01-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_appointment_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesorprofile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Biografía Completa'),
        ),
        migrations.AddField(
            model_name='asesorprofile',
            name='specialty',
            field=models.CharField(default='Consultor', max_length=100, verbose_name='Especialidad'),
        ),
    ]
