# Generated by Django 6.0 on 2026-01-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_appointment_payment_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoporteUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FELICITACION', '🎉 Felicitación'), ('SUGERENCIA', '💡 Sugerencia'), ('RECLAMO', '⚠️ Reclamo')], default='SUGERENCIA', max_length=20)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reclamos/', verbose_name='Adjuntar Archivo')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
            ],
        ),
    ]
