# Generated by Django 6.0 on 2026-01-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_asesorprofile_description_asesorprofile_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
