# Generated by Django 6.0 on 2026-01-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_soporteusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='comuna_facturacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='email_facturacion',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Facturación'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='giro_facturacion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Giro'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='nombre_facturacion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre / Razón Social'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rut_facturacion',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='RUT'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='telefono_facturacion',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='tipo_documento',
            field=models.CharField(choices=[('BOLETA', 'Boleta'), ('FACTURA', 'Factura')], default='BOLETA', max_length=10),
        ),
    ]
