# Generated by Django 6.0 on 2026-01-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_appointment_client_address_appointment_client_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='estado_reclamo',
            field=models.CharField(choices=[('SIN_RECLAMO', 'Sin Reclamo'), ('PENDIENTE', 'Revisión Pendiente (Jefe)'), ('APROBADO', 'Reembolso Aprobado'), ('RECHAZADO', 'Reclamo Rechazado')], default='SIN_RECLAMO', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reclamo_mensaje',
            field=models.TextField(blank=True, help_text='Razón del reclamo del cliente', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='meeting_link',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace a Sala de Reunión (Zoom/Meet)'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_token',
            field=models.CharField(blank=True, help_text='Referencia interna, NO es la tarjeta.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('POR_PAGAR', 'Aprobada - Esperando Pago'), ('CONFIRMADA', 'Pagada y Confirmada'), ('FINALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada'), ('REEMBOLSADO', 'Dinero Devuelto')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ASESOR', 'Asesor (Oferente)'), ('CLIENTE', 'Cliente (Busca servicio)')], default='CLIENTE', max_length=10),
        ),
    ]
