# Generated by Django 6.0 on 2026-02-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_appointment_comuna_facturacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-start_datetime']},
        ),
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['fecha']},
        ),
    ]
